language: ruby

env:
  global:
    - COVERAGE=true
  matrix:
    - TEST_SUITE=integration
    - TEST_SUITE=functional

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database converge_sink;' -U postgres

script: "bundle exec rake test:$TEST_SUITE"

rvm:
  - "1.9.3"
  - "2.1.3"
  - "ruby-head"
  - "jruby-19mode"
  - "rbx-2"
